

package:
  name: load_setup_py_test
  version: {{ load_setup_py_data().version }}

source:
  git_url: https://github.com/NCAR/load_setup_py_test

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - numpy x.x
    - gcc
    - python
    - libgcc 4.8.5

  run:
    - numpy x.x
    - python
    - libgcc 4.8.5

test:
  requires:
    - nose
  imports:
    - fortest 
  #commands:
    #- cd $SRC_DIR/src/examples && for file in xy2.py; do echo $file ; nosetests $file ; done | tee fortest-test.log


